/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

import { createClient } from '@supabase/supabase-js';

export const projectId = "lymkwugkfeamqkiybntd"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx5bWt3dWdrZmVhbXFraXlibnRkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjAyMTM1MjAsImV4cCI6MjA3NTc4OTUyMH0.p4T2Ul22BO8dEacr847k91CfGpG2ZDNvHudO6bcV6Ec"

const supabaseUrl = `https://${projectId}.supabase.co`;

export const supabase = createClient(supabaseUrl, publicAnonKey, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
  },
  realtime: {
    params: {
      eventsPerSecond: 10
    }
  }
});